services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - stash
    networks:
      - internal

  stash:
    ports: !override []
    networks:
      - internal

networks:
  internal:
